const MainActionTypes = {
  ADD_GAME: 'ADD_GAME',
  DELETE_GAME: 'DELETE_GAME',
  ADD_WORKSHOP_ITEM: 'ADD_WORKSHOP_ITEM',
  DELETE_WORKSHOP_ITEM: 'DELETE_WORKSHOP_ITEM'
}

export default MainActionTypes