const SettingActionTypes = {
  CHANGE_INTERVAL: 'CHANGE_INTERVAL',
  ADD_STEAMCMD_LOCATION: 'ADD_STEAMCMD_LOCATION',
  CHANGE_STEAMCMD_LOCATION: 'CHANGE_STEAMCMD_LOCATION'
}

export default SettingActionTypes